sudo: required

arch:
  repos:
    - jelle=http://pkgbuild.com/~jelle/repo/x86_64

  packages:
    - python
    - python-nose

  script:
    - yes | pacman -S pacman-git
    - python3 -m py_compile $(git ls-files '*.py')
    - sudo python3 setup.py install
    - python3 setup.py test

script: 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'

# vim: ft=yaml ts=2 sw=2 et:

